export const data = {
  items: [
    {
      id: 1,
      name: "Cookies - Fortune",
      price: "$7.90",
      photo: "http://dummyimage.com/236x100.png/ff4444/ffffff",
    },
    {
      id: 2,
      name: "Pie Pecan",
      price: "$9.65",
      photo: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    },
    {
      id: 3,
      name: "Chicken Thigh - Bone Out",
      price: "$2.97",
      photo: "http://dummyimage.com/123x100.png/5fa2dd/ffffff",
    },
    {
      id: 4,
      name: "Oil - Truffle, Black",
      price: "$7.62",
      photo: "http://dummyimage.com/150x100.png/cc0000/ffffff",
    },
    {
      id: 5,
      name: "Bread - Olive Dinner Roll",
      price: "$6.16",
      photo: "http://dummyimage.com/168x100.png/cc0000/ffffff",
    },
    {
      id: 6,
      name: "Trout - Rainbow, Fresh",
      price: "$1.74",
      photo: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
    },
    {
      id: 7,
      name: "Nescafe - Frothy French Vanilla",
      price: "$7.32",
      photo: "http://dummyimage.com/161x100.png/cc0000/ffffff",
    },
    {
      id: 8,
      name: "Sauce - Thousand Island",
      price: "$6.99",
      photo: "http://dummyimage.com/223x100.png/dddddd/000000",
    },
    {
      id: 9,
      name: "Cheese - Mozzarella, Shredded",
      price: "$8.94",
      photo: "http://dummyimage.com/160x100.png/cc0000/ffffff",
    },
    {
      id: 10,
      name: "Pork - Ground",
      price: "$3.19",
      photo: "http://dummyimage.com/160x100.png/ff4444/ffffff",
    },
    {
      id: 11,
      name: "Bread - Sour Batard",
      price: "$9.21",
      photo: "http://dummyimage.com/250x100.png/ff4444/ffffff",
    },
    {
      id: 12,
      name: "Paper - Brown Paper Mini Cups",
      price: "$0.14",
      photo: "http://dummyimage.com/221x100.png/dddddd/000000",
    },
    {
      id: 13,
      name: "Buffalo - Striploin",
      price: "$3.63",
      photo: "http://dummyimage.com/233x100.png/dddddd/000000",
    },
    {
      id: 14,
      name: "Cake Sheet Combo Party Pack",
      price: "$9.32",
      photo: "http://dummyimage.com/130x100.png/cc0000/ffffff",
    },
    {
      id: 15,
      name: "Table Cloth 81x81 Colour",
      price: "$5.09",
      photo: "http://dummyimage.com/124x100.png/dddddd/000000",
    },
    {
      id: 16,
      name: "Lamb - Whole Head Off,nz",
      price: "$8.87",
      photo: "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
    },
    {
      id: 17,
      name: "Cheese - Cheddarsliced",
      price: "$0.47",
      photo: "http://dummyimage.com/203x100.png/ff4444/ffffff",
    },
    {
      id: 18,
      name: "Pork - Bacon, Double Smoked",
      price: "$1.50",
      photo: "http://dummyimage.com/193x100.png/5fa2dd/ffffff",
    },
    {
      id: 19,
      name: "Pasta - Tortellini, Fresh",
      price: "$1.20",
      photo: "http://dummyimage.com/123x100.png/ff4444/ffffff",
    },
    {
      id: 20,
      name: "Corn Shoots",
      price: "$5.84",
      photo: "http://dummyimage.com/229x100.png/cc0000/ffffff",
    },
    {
      id: 21,
      name: "Lettuce - Escarole",
      price: "$9.16",
      photo: "http://dummyimage.com/124x100.png/ff4444/ffffff",
    },
  ],
};
